spring:
  profiles:
    group:
      "prod": "local_setting,common"
      "local": "local_setting,common"
      "test": "test_setting,common"

server:
  port: 80

---

# common setting
spring:
  config:
    activate:
      on-profile: "common"
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis-mapper/*.xml

---

spring:
  config.activate.on-profile: local_setting
  datasource:
    url: "jdbc:mysql://localhost:3306/bhdb"
    username: "bhuser"
    password: "bhpw"
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
logging:
  file:
    path: /home/behavior/logs-test
  level:
    root: info

---

spring:
  config.activate.on-profile: test_setting
  datasource:
    url: "jdbc:mysql://localhost:3306/bhdb_test"
    username: "bhuser_test"
    password: "bhpw_test"
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
logging:
  file:
    path: C:/Behavior-logs/logs
  level:
    root: info
    '[roadiary.behavior.category]': trace
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
